/api/v1/config/maintenance_tasks/search:
  description: |-
    pf::UnifiedApi::Controller::Config::MaintenanceTasks

      form_process_parameters_for_cleanup
        form_process_parameters_for_cleanup
  post:
    description: Search all items.
    operationId: api.v1.Config.MaintenanceTasks.search
    parameters: []
    requestBody:
      content:
        application/json:
          example:
            cursor: 0
            limit: 25
          schema:
            allOf:
            - $ref: '#/components/schemas/Search'
            - properties:
                cursor:
                  type: string
                fields:
                  items:
                    type: string
                  type: array
                limit:
                  maximum: 1000
                  minimum: 1
                  type: integer
                sort:
                  items:
                    type: string
                  type: array
              required:
              - fields
              - sort
      description: Search for items.
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigMaintenanceTasksList'
        description: Request successful. Response contains a list of resources.
      '401':
        $ref: '#/components/responses/Forbidden'
    tags:
    - Config/MaintenanceTasks
