/api/v1/config/filter_engines/provisioning_filters/bulk_update:
  description: Configure vlan filters
  patch:
    description: Update one or more items.
    operationId: api.v1.Config.FilterEngines.Provisioning.bulk_update
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            properties:
              items:
                items:
                  $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilter'
                type: array
            type: object
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterWrapped'
        description: Request successful. Response contains a specific resource.
      '401':
        $ref: '#/components/responses/Forbidden'
      '404':
        $ref: '#/components/responses/NotFound'
    tags:
    - Config/FilterEngines/ProvisioningFilters
