/api/v1/config/filter_engines/provisioning_filters/sort_items:
  description: Configure vlan filters
  patch:
    description: Sort items.
    operationId: api.v1.Config.FilterEngines.Provisioning.sort_items
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterWrapped'
        description: Request successful. Response contains a specific resource.
      '401':
        $ref: '#/components/responses/Forbidden'
      '404':
        $ref: '#/components/responses/NotFound'
    tags:
    - Config/FilterEngines/ProvisioningFilters
