ConfigPortalModuleSubTypeSelectrole:
  properties:
    actions:
      description: Actions
      items:
        description: Action
        properties:
          type:
            description: Type
            type: string
          value:
            description: Value
            type: string
        type: object
      type: array
    admin_role:
      description: Which roles should have access to this module to select the role
      items:
        description: Which roles should have access to this module to select the role
        type: string
      type: array
    description:
      description: The description that will be displayed to users
      type: string
    id:
      description: Identifier
      type: string
    list_role:
      description: Which roles can be select
      items:
        description: Which roles can be select
        type: string
      type: array
    template:
      description: The template to use
      type: string
    type:
      default: SelectRole
      description: Discriminator `SelectRole`
      type: string
  required:
  - id
  - description
  type: object
