ConfigSourceSubTypePaypal:
  properties:
    cert_file:
      description: The path to the certificate you submitted to Paypal.
      type: string
    cert_file_upload:
      description: Cert file upload
      type: string
    cert_id:
      description: Cert id
      type: string
    create_local_account:
      description: Create a local account on the PacketFence system based on the username
        provided.
      type: string
    currency:
      description: Currency
      type: string
    description:
      description: Description
      type: string
    domains:
      description: Comma separated list of domains that will be resolve with the correct
        IP addresses.
      type: string
    email_address:
      description: The email address associated to your paypal account.
      type: string
    hash_passwords:
      description: The algorithm used to hash the passwords in the database.This will
        only affect newly created or reset passwords.
      type: string
    id:
      description: Id
      type: string
    identity_token:
      description: Identity token
      type: string
    key_file:
      description: The path to the associated key of the certificate you submitted
        to Paypal.
      type: string
    key_file_upload:
      description: Key file upload
      type: string
    local_account_expiration:
      description: Local account expiration
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    local_account_logins:
      description: The amount of times, the local account can be used after its created.
        0 means infinite.
      type: integer
    password_length:
      description: The length of the password to generate.
      type: integer
    payment_type:
      description: The type of transactions this source will do (donations or sales).
      type: string
    paypal_cert_file:
      description: The path to the Paypal certificate you downloaded.
      type: string
    paypal_cert_file_upload:
      description: Paypal cert file upload
      type: string
    send_email_confirmation:
      description: Send billing confirmation
      type: string
    test_mode:
      description: Test mode
      type: string
    type:
      default: Paypal
      description: Discriminator `Paypal`
      type: string
  required:
  - id
  - description
  - hash_passwords
  - password_length
  - identity_token
  - cert_id
  - email_address
  - payment_type
  - domains
  type: object
