ConfigPortalModuleSubTypeUrl:
  properties:
    actions:
      description: Actions
      items:
        description: Action
        properties:
          type:
            description: Type
            type: string
          value:
            description: Value
            type: string
        type: object
      type: array
    description:
      description: The description that will be displayed to users
      type: string
    id:
      description: Identifier
      type: string
    skipable:
      description: Whether or not, this redirection can be skipped.
      type: string
    type:
      default: URL
      description: Discriminator `URL`
      type: string
    url:
      description: The URL on which the user should be redirected.
      type: string
  required:
  - id
  - description
  - url
  type: object
