ConfigPortalModuleSubTypeMessage:
  properties:
    actions:
      description: Actions
      items:
        description: Action
        properties:
          type:
            description: Type
            type: string
          value:
            description: Value
            type: string
        type: object
      type: array
    description:
      description: The description that will be displayed to users
      type: string
    id:
      description: Identifier
      type: string
    message:
      description: The message that will be displayed to the user. Use with caution
        as the HTML contained in this field will NOT be escaped.
      type: string
    skipable:
      description: Whether or not, this message can be skipped
      type: string
    template:
      description: The template to use to display the message
      type: string
    type:
      default: Message
      description: Discriminator `Message`
      type: string
    with_layout:
      description: Enable Layout
      type: string
  required:
  - id
  - description
  - message
  type: object
