ConfigMaintenanceTaskSubTypeCleanupChiDatabaseCache:
  properties:
    batch:
      description: Amount of items that will be processed in each batch of this task.
        Batches are executed until there is no more items to process or until the
        timeout is reached.
      type: integer
    id:
      description: Pfcron Name
      type: string
    schedule:
      description: The schedule for maintenance task (cron like spec).
      type: string
    status:
      description: Whether or not this task is enabled.<br>Requires a restart of pfcron
        to be effective.
      type: string
    timeout:
      description: Maximum amount of time this task can run.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    type:
      default: cleanup_chi_database_cache
      description: Discriminator `cleanup_chi_database_cache`
      type: string
  required:
  - id
  - type
  type: object
