ConfigSourceSubTypeSms:
  properties:
    administration_rules:
      description: Administration rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    authentication_rules:
      description: Authentication rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    create_local_account:
      description: Create a local account on the PacketFence system based on the username
        provided.
      type: string
    description:
      description: Description
      type: string
    hash_passwords:
      description: The algorithm used to hash the passwords in the database.This will
        only affect newly created or reset passwords.
      type: string
    id:
      description: Id
      type: string
    local_account_expiration:
      description: Local account expiration
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    local_account_logins:
      description: The amount of times, the local account can be used after its created.
        0 means infinite.
      type: integer
    message:
      description: SMS text message ($pin will be replaced by the PIN number)
      type: string
    password_length:
      description: The length of the password to generate.
      type: integer
    pin_code_length:
      description: The amount of digits of the PIN number.
      type: integer
    sms_activation_timeout:
      description: This is the delay given to a guest who registered by SMS confirmation
        to fill the PIN code.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    sms_carriers:
      description: List of phone carriers available to the user
      items:
        description: List of phone carriers available to the user
        type: string
      type: array
    type:
      default: SMS
      description: Discriminator `SMS`
      type: string
  required:
  - id
  - description
  - hash_passwords
  - password_length
  - sms_activation_timeout
  - pin_code_length
  type: object
