ConfigSourceSubTypeKerberos:
  properties:
    administration_rules:
      description: Administration rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    authenticate_realm:
      description: Realm to use to authenticate
      type: string
    authentication_rules:
      description: Authentication rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    description:
      description: Description
      type: string
    host:
      description: Host
      type: string
    id:
      description: Id
      type: string
    realms:
      description: Realms that will be associated with this source (For the Portal/Admin
        GUI/RADIUS post-auth, not for FreeRADIUS proxy)
      items:
        description: Realms that will be associated with this source (For the Portal/Admin
          GUI/RADIUS post-auth, not for FreeRADIUS proxy)
        type: string
      type: array
    type:
      default: Kerberos
      description: Discriminator `Kerberos`
      type: string
  required:
  - id
  - description
  - host
  - authenticate_realm
  type: object
