ConfigMfaSubTypeTotp:
  properties:
    cache_duration:
      description: Cache duration
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    id:
      description: Id
      type: string
    post_mfa_validation_cache_duration:
      description: Post mfa validation cache duration
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    radius_mfa_method:
      description: Radius mfa method
      type: string
    scope:
      description: Scope
      type: string
    split_char:
      description: Split char
      type: string
    type:
      default: TOTP
      description: Discriminator `TOTP`
      type: string
  required:
  - id
  - split_char
  - radius_mfa_method
  type: object
