ConfigProvisioningSubTypeDeny:
  properties:
    apply_role:
      description: When enabled, this will apply the configured role to the endpoint
        if it is authorized in the provisioner.
      type: string
    autoregister:
      description: Whether or not devices should be automatically registered on the
        network if they are authorized in the provisioner.
      type: string
    category:
      description: Nodes with the selected roles will be affected
      items:
        description: Nodes with the selected roles will be affected
        type: string
      type: array
    description:
      description: Description
      type: string
    enforce:
      description: Whether or not the provisioner should be enforced. This will trigger
        checks to validate the device is compliant with the provisioner during RADIUS
        authentication and on the captive portal.
      type: string
    id:
      description: Provisioning ID
      type: string
    non_compliance_security_event:
      description: Which security event should be raised when non compliance is detected
      type: string
    oses:
      description: Nodes with the selected OS will be affected
      items:
        description: Nodes with the selected OS will be affected
        type: string
      type: array
    pki_provider:
      description: PKI Provider
      type: string
    role_to_apply:
      description: When "Apply role" is enabled, this defines the role to apply when
        the device is authorized with the provisioner.
      type: string
    rules:
      description: Rules to be applied
      items:
        description: Rules to be applied
        type: string
      type: array
    sync_pid:
      description: Whether or not the PID (username) should be synchronized from the
        provisioner to PacketFence.
      type: string
    type:
      default: deny
      description: Discriminator `deny`
      type: string
  required:
  - id
  - type
  type: object
