ConfigPortalModuleSubTypeMfa:
  properties:
    actions:
      description: Actions
      items:
        description: Action
        properties:
          type:
            description: Type
            type: string
          value:
            description: Value
            type: string
        type: object
      type: array
    description:
      description: The description that will be displayed to users
      type: string
    id:
      description: Identifier
      type: string
    type:
      default: MFA
      description: Discriminator `MFA`
      type: string
  required:
  - id
  - description
  type: object
