ConfigMaintenanceTaskSubTypeCertificatesCheck:
  properties:
    certificates:
      description: SSL certificate(s) to monitor. Comma-delimited list
      type: string
    delay:
      description: Minimum gap before certificate expiration date (will the certificate
        expires in ...)
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    id:
      description: Pfcron Name
      type: string
    schedule:
      description: The schedule for maintenance task (cron like spec).
      type: string
    status:
      description: Whether or not this task is enabled.<br>Requires a restart of pfcron
        to be effective.
      type: string
    type:
      default: certificates_check
      description: Discriminator `certificates_check`
      type: string
  required:
  - id
  - type
  type: object
