ConfigPortalModuleSubTypeSslInspection:
  properties:
    actions:
      description: Actions
      items:
        description: Action
        properties:
          type:
            description: Type
            type: string
          value:
            description: Value
            type: string
        type: object
      type: array
    description:
      description: The description that will be displayed to users
      type: string
    id:
      description: Identifier
      type: string
    skipable:
      description: Whether or not, this message can be skipped
      type: string
    ssl_mobileconfig_path:
      description: URL of an iOS mobileconfig profile to install the certificate.
      type: string
    ssl_path:
      description: URL of the SSL certificate in X509 Base64 format.
      type: string
    type:
      default: SSL_Inspection
      description: Discriminator `SSL_Inspection`
      type: string
  required:
  - id
  - description
  - ssl_mobileconfig_path
  - ssl_path
  type: object
