ConfigSourceSubTypeWindowslive:
  properties:
    access_token_param:
      description: Access Token Parameter
      type: string
    access_token_path:
      description: API Token Path
      type: string
    administration_rules:
      description: Administration rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    authentication_rules:
      description: Authentication rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    authorize_path:
      description: API Authorize Path
      type: string
    client_id:
      description: API ID
      type: string
    client_secret:
      description: API Secret
      type: string
    create_local_account:
      description: Create a local account on the PacketFence system based on the username
        provided.
      type: string
    description:
      description: Description
      type: string
    domains:
      description: Comma separated list of domains that will be resolve with the correct
        IP addresses.
      type: string
    hash_passwords:
      description: The algorithm used to hash the passwords in the database.This will
        only affect newly created or reset passwords.
      type: string
    id:
      description: Id
      type: string
    local_account_expiration:
      description: Local account expiration
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    local_account_logins:
      description: The amount of times, the local account can be used after its created.
        0 means infinite.
      type: integer
    password_length:
      description: The length of the password to generate.
      type: integer
    protected_resource_url:
      description: API URL of logged user
      type: string
    redirect_url:
      description: The hostname must be the one of your captive portal.
      type: string
    scope:
      description: The permissions the application requests.
      type: string
    site:
      description: API URL
      type: string
    type:
      default: WindowsLive
      description: Discriminator `WindowsLive`
      type: string
  required:
  - id
  - description
  - hash_passwords
  - password_length
  - client_id
  - client_secret
  - site
  - authorize_path
  - access_token_path
  - access_token_param
  - scope
  - protected_resource_url
  - redirect_url
  - domains
  type: object
