ConfigMaintenanceTaskSubTypeUbiquitiApMacToIp:
  properties:
    id:
      description: Pfcron Name
      type: string
    schedule:
      description: The schedule for maintenance task (cron like spec).
      type: string
    status:
      description: Whether or not this task is enabled.<br>Requires a restart of pfcron
        to be effective.
      type: string
    type:
      default: ubiquiti_ap_mac_to_ip
      description: Discriminator `ubiquiti_ap_mac_to_ip`
      type: string
  required:
  - id
  - type
  type: object
