ConfigSourceSubTypeBlackhole:
  properties:
    description:
      description: Description
      type: string
    id:
      description: Id
      type: string
    type:
      default: Blackhole
      description: Discriminator `Blackhole`
      type: string
  required:
  - id
  - description
  type: object
