ConfigMaintenanceTaskSubTypeBandwidthMaintenance:
  properties:
    batch:
      description: Amount of items that will be processed in each batch of this task.
        Batches are executed until there is no more items to process or until the
        timeout is reached.
      type: integer
    history_batch:
      description: Amount of items that will be processed in each batch of this task.
        Batches are executed until there is no more items to process or until the
        timeout is reached.
      type: integer
    history_timeout:
      description: Maximum amount of time this task can run.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    history_window:
      description: Maximum amount of time this task can run.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    id:
      description: Pfcron Name
      type: string
    schedule:
      description: The schedule for maintenance task (cron like spec).
      type: string
    session_batch:
      description: Amount of items that will be processed in each batch of this task.
        Batches are executed until there is no more items to process or until the
        timeout is reached.
      type: integer
    session_timeout:
      description: Maximum amount of time this task can run.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    session_window:
      description: Maximum amount of time this task can run.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    status:
      description: Whether or not this task is enabled.<br>Requires a restart of pfcron
        to be effective.
      type: string
    timeout:
      description: Maximum amount of time this task can run.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    type:
      default: bandwidth_maintenance
      description: Discriminator `bandwidth_maintenance`
      type: string
    window:
      description: Maximum amount of time this task can run.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
  required:
  - id
  - type
  type: object
