ConfigSourceSubTypeGoogleworkspaceldap:
  properties:
    administration_rules:
      description: Administration rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    append_to_searchattributes:
      description: Append this ldap filter to the generated generated ldap filter
        generated for the search attributes.
      type: string
    authentication_rules:
      description: Authentication rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    basedn:
      description: Basedn
      type: string
    binddn:
      description: Leave this field empty if you want to perform an anonymous bind.
      type: string
    ca_file:
      description: Ca file
      type: string
    ca_file_upload:
      description: Ca file upload
      type: string
    cache_match:
      description: Will cache results of matching a rule
      type: string
    client_cert_file:
      description: Client cert file
      type: string
    client_cert_file_upload:
      description: Client cert file upload
      type: string
    client_key_file:
      description: Client key file
      type: string
    client_key_file_upload:
      description: Client key file upload
      type: string
    connection_timeout:
      description: LDAP connection Timeout
      type: string
    dead_duration:
      description: Dead duration
      type: integer
    description:
      description: Description
      type: string
    email_attribute:
      description: LDAP attribute name that stores the email address against which
        the filter will match.
      type: string
    encryption:
      description: Encryption
      type: string
    host:
      description: Host
      items:
        description: Host
        type: string
      type: array
    id:
      description: Id
      type: string
    monitor:
      description: Do you want to monitor this source?
      type: string
    password:
      description: Password
      type: string
    port:
      description: Port
      type: integer
    read_timeout:
      description: LDAP response timeout
      type: string
    realms:
      description: Realms that will be associated with this source (For the Portal/Admin
        GUI/RADIUS post-auth, not for FreeRADIUS proxy)
      items:
        description: Realms that will be associated with this source (For the Portal/Admin
          GUI/RADIUS post-auth, not for FreeRADIUS proxy)
        type: string
      type: array
    scope:
      description: Scope
      type: string
    searchattributes:
      description: Other attributes that can be used as the username (requires to
        restart the radiusd service to be effective)
      items:
        description: Other attributes that can be used as the username (requires to
          restart the radiusd service to be effective)
        type: string
      type: array
    shuffle:
      description: Randomly choose LDAP server to query
      type: string
    type:
      default: GoogleWorkspaceLDAP
      description: Discriminator `GoogleWorkspaceLDAP`
      type: string
    use_connector:
      description: Use connector
      type: string
    usernameattribute:
      description: Main reference attribute that contain the username
      type: string
    verify:
      description: Verify
      type: string
    write_timeout:
      description: LDAP request timeout
      type: string
  required:
  - id
  - description
  - host
  - encryption
  - basedn
  - scope
  - usernameattribute
  - client_cert_file
  - client_key_file
  type: object
