ConfigPortalModuleSubTypeAuthenticationBilling:
  properties:
    aup_template:
      description: The template to use for the AUP
      type: string
    custom_fields:
      description: The additionnal fields that should be required for registration
      items:
        description: The additionnal fields that should be required for registration
        type: string
      type: array
    description:
      description: The description that will be displayed to users
      type: string
    fields_to_save:
      description: These fields will be saved through the registration process
      items:
        description: These fields will be saved through the registration process
        type: string
      type: array
    id:
      description: Identifier
      type: string
    multi_source_ids:
      description: Multi source ids
      items:
        description: Multi source id
        type: string
      type: array
    pid_field:
      description: Which field should be used as the PID.
      type: string
    signup_template:
      description: The template to use for the signup
      type: string
    type:
      default: Authentication::Billing
      description: Discriminator `Authentication::Billing`
      type: string
    with_aup:
      description: Require the user to accept the AUP
      type: string
  required:
  - id
  - description
  - aup_template
  type: object
