ConfigMaintenanceTaskSubTypeSwitchCacheLldplocalportDescription:
  properties:
    id:
      description: Pfcron Name
      type: string
    process_switchranges:
      description: Whether or not a switch range should be expanded to process each
        of its IPs
      type: string
    schedule:
      description: The schedule for maintenance task (cron like spec).
      type: string
    status:
      description: Whether or not this task is enabled.<br>Requires a restart of pfcron
        to be effective.
      type: string
    type:
      default: switch_cache_lldpLocalPort_description
      description: Discriminator `switch_cache_lldpLocalPort_description`
      type: string
  required:
  - id
  - type
  type: object
