ConfigPkiProviderSubTypePacketfenceLocal:
  properties:
    ca_cert_path:
      description: Path of the CA certificate used to generate client certificate/key
        combination
      type: string
    ca_cert_path_upload:
      description: Ca cert path upload
      type: string
    client_cert_path:
      description: Path of the client cert that will be used to generate the p12
      type: string
    client_cert_path_upload:
      description: Client cert path upload
      type: string
    client_key_path:
      description: Path of the client key that will be used to generate the p12
      type: string
    client_key_path_upload:
      description: Client key path upload
      type: string
    id:
      description: Id
      type: string
    server_cert_path:
      description: Path of the RADIUS server authentication certificate
      type: string
    server_cert_path_upload:
      description: Server cert path upload
      type: string
    type:
      default: packetfence_local
      description: Discriminator `packetfence_local`
      type: string
  required:
  - id
  - type
  type: object
