ConfigSourceSubTypeEduroam:
  properties:
    administration_rules:
      description: Administration rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    auth_listening_port:
      description: Auth listening port
      type: integer
    authentication_rules:
      description: Authentication rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    description:
      description: Description
      type: string
    eduroam_operator_name:
      description: Eduroam operator name
      type: string
    eduroam_options:
      description: Eduroam options
      type: string
    eduroam_radius_auth:
      description: Eduroam radius auth
      items:
        description: Eduroam radius auth
        type: string
      type: array
    eduroam_radius_auth_proxy_type:
      description: Eduroam radius auth proxy type
      type: string
    id:
      description: Id
      type: string
    local_realm:
      description: Local realm
      items:
        description: Local realm
        type: string
      type: array
    reject_realm:
      description: Reject realm
      items:
        description: Reject realm
        type: string
      type: array
    type:
      default: Eduroam
      description: Discriminator `Eduroam`
      type: string
  required:
  - id
  - description
  - eduroam_radius_auth_proxy_type
  type: object
