ConfigSyslogForwarderSubTypeServer:
  properties:
    all_logs:
      description: All logs
      type: string
    host:
      description: Host
      type: string
    id:
      description: Syslog Name
      type: string
    logs:
      description: Logs
      items:
        description: Logs
        type: string
      type: array
    port:
      description: Port
      type: integer
    proto:
      description: Proto
      type: string
    type:
      default: server
      description: Discriminator `server`
      type: string
  required:
  - id
  - type
  - proto
  - host
  - port
  type: object
