ConfigPortalModuleSubTypeChoice:
  properties:
    actions:
      description: Actions
      items:
        description: Action
        properties:
          type:
            description: Type
            type: string
          value:
            description: Value
            type: string
        type: object
      type: array
    description:
      description: The description that will be displayed to users
      type: string
    id:
      description: Identifier
      type: string
    modules:
      description: Modules
      items:
        description: Module
        type: string
      type: array
    show_first_module_on_default:
      description: Show first module when none is selected
      type: string
    template:
      description: The template to use to display the choices
      type: string
    type:
      default: Choice
      description: Discriminator `Choice`
      type: string
  required:
  - id
  - description
  type: object
