ConfigMaintenanceTaskSubTypePfflow:
  properties:
    group_id:
      description: 'The Kafka Consumer Group ID '
      type: string
    id:
      description: Pfcron Name
      type: string
    kafka_brokers:
      description: Kafka Brokers
      type: string
    read_topic:
      description: The Kafka topic to read pfflows from
      type: string
    schedule:
      description: The schedule for maintenance task (cron like spec).
      type: string
    send_topic:
      description: The Kafka topic to write network events to
      type: string
    status:
      description: Whether or not this task is enabled.<br>Requires a restart of pfcron
        to be effective.
      type: string
    submit_batch:
      description: Amount of items that will be processed in each batch of this task.
        Batches are executed until there is no more items to process or until the
        timeout is reached.
      type: integer
    type:
      default: pfflow
      description: Discriminator `pfflow`
      type: string
  required:
  - id
  - type
  type: object
