ConfigDomainsMeta:
  properties:
    meta:
      properties:
        ad_account_lockout_duration:
          $ref: '#/components/schemas/Meta'
        ad_account_lockout_threshold:
          $ref: '#/components/schemas/Meta'
        ad_fqdn:
          $ref: '#/components/schemas/Meta'
        ad_old_password_allowed_period:
          $ref: '#/components/schemas/Meta'
        ad_reset_account_lockout_counter_after:
          $ref: '#/components/schemas/Meta'
        ad_server:
          $ref: '#/components/schemas/Meta'
        bind_dn:
          $ref: '#/components/schemas/Meta'
        bind_pass:
          $ref: '#/components/schemas/Meta'
        dns_name:
          $ref: '#/components/schemas/Meta'
        dns_servers:
          $ref: '#/components/schemas/Meta'
        id:
          $ref: '#/components/schemas/Meta'
        machine_account_password:
          $ref: '#/components/schemas/Meta'
        max_allowed_password_attempts_per_device:
          $ref: '#/components/schemas/Meta'
        nt_key_cache_enabled:
          $ref: '#/components/schemas/Meta'
        nt_key_cache_expire:
          $ref: '#/components/schemas/Meta'
        ntlm_auth_host:
          $ref: '#/components/schemas/Meta'
        ntlm_auth_port:
          $ref: '#/components/schemas/Meta'
        ntlm_cache:
          $ref: '#/components/schemas/Meta'
        ntlm_cache_expiry:
          $ref: '#/components/schemas/Meta'
        ntlm_cache_source:
          $ref: '#/components/schemas/Meta'
        ou:
          $ref: '#/components/schemas/Meta'
        password_is_nt_hash:
          $ref: '#/components/schemas/Meta'
        registration:
          $ref: '#/components/schemas/Meta'
        server_name:
          $ref: '#/components/schemas/Meta'
        status:
          $ref: '#/components/schemas/Meta'
        sticky_dc:
          $ref: '#/components/schemas/Meta'
        workgroup:
          $ref: '#/components/schemas/Meta'
      type: object
  type: object
