ConfigSourceSubTypeHttp:
  properties:
    authentication_url:
      description: 'Note : The URL is always prefixed by a slash (/)'
      type: string
    authorization_url:
      description: 'Note : The URL is always prefixed by a slash (/)'
      type: string
    description:
      description: Description
      type: string
    host:
      description: Host
      type: string
    id:
      description: Id
      type: string
    password:
      description: API password (basic auth)
      type: string
    port:
      description: Port
      type: integer
    protocol:
      description: Encryption
      type: string
    realms:
      description: Realms that will be associated with this source (For the Portal/Admin
        GUI/RADIUS post-auth, not for FreeRADIUS proxy)
      items:
        description: Realms that will be associated with this source (For the Portal/Admin
          GUI/RADIUS post-auth, not for FreeRADIUS proxy)
        type: string
      type: array
    type:
      default: HTTP
      description: Discriminator `HTTP`
      type: string
    username:
      description: API username (basic auth)
      type: string
  required:
  - id
  - description
  - protocol
  - authentication_url
  - authorization_url
  type: object
