ConfigPortalModuleSubTypeFixedrole:
  properties:
    actions:
      description: Actions
      items:
        description: Action
        properties:
          type:
            description: Type
            type: string
          value:
            description: Value
            type: string
        type: object
      type: array
    description:
      description: The description that will be displayed to users
      type: string
    id:
      description: Identifier
      type: string
    stone_roles:
      description: Nodes with the selected roles will be affected
      items:
        description: Nodes with the selected roles will be affected
        type: string
      type: array
    type:
      default: FixedRole
      description: Discriminator `FixedRole`
      type: string
  required:
  - id
  - description
  type: object
