ConfigFilterEnginesProvisioningFilter:
  description: 'Choose one of the request bodies by discriminator (`type`). '
  discriminator:
    mapping:
      accept: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeAccept'
      airwatch: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeAirwatch'
      android: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeAndroid'
      deny: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeDeny'
      dpsk: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeDpsk'
      google_workspace_chromebook: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeGoogleWorkspaceChromebook'
      intune: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeIntune'
      jamf: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeJamf'
      kandji: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeKandji'
      lookup: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeLookup'
      mobileconfig: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeMobileconfig'
      mobileiron: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeMobileiron'
      sentinelone: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeSentinelone'
      windows: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeWindows'
    propertyName: type
  oneOf:
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeAccept'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeAirwatch'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeAndroid'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeDeny'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeDpsk'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeGoogleWorkspaceChromebook'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeIntune'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeJamf'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeKandji'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeLookup'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeMobileconfig'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeMobileiron'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeSentinelone'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeWindows'
