ConfigScanSubTypePfappserverFormConfigScanRapid7:
  properties:
    categories:
      description: Nodes with the selected roles will be affected
      items:
        description: Nodes with the selected roles will be affected
        type: string
      type: array
    duration:
      description: Approximate duration of a scan. User being scanned on registration
        are presented a progress bar for this duration, afterwards the browser refreshes
        until scan is complete.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    engine_id:
      description: The identifier of the scan engine to use when scanning the devices.
      type: string
    host:
      description: Hostname or IP Address
      type: string
    id:
      description: Name
      type: string
    oses:
      description: Nodes with the selected OS will be affected
      items:
        description: Nodes with the selected OS will be affected
        type: string
      type: array
    password:
      description: Password
      type: string
    port:
      description: If you use an alternative port, please specify
      type: integer
    post_registration:
      description: If this option is enabled, the PF system will scan host after on
        the production vlan. This will not work for devices that are in an inline
        VLAN.
      type: string
    pre_registration:
      description: If this option is enabled, the PF system will scan host before
        the registration.
      type: string
    registration:
      description: If this option is enabled, the PF system will scan each host after
        registration is complete.
      type: string
    site_id:
      description: The identifier of the site to scan (the site where the hosts are
        located)
      type: string
    template_id:
      description: The scan template to use for scanning the clients.
      type: string
    type:
      default: pfappserver::Form::Config::Scan::Rapid7
      description: Discriminator `pfappserver::Form::Config::Scan::Rapid7`
      type: string
    username:
      description: Username
      type: string
    verify_hostname:
      description: Verify hostname of server when connecting to the API
      type: string
  required:
  - id
  - username
  - password
  - host
  type: object
