ConfigSourceSubTypeSaml:
  properties:
    authorization_source_id:
      description: The source to use for authorization (rule matching)
      type: string
    description:
      description: Description
      type: string
    id:
      description: Id
      type: string
    idp_ca_cert_path:
      description: If your Identity Provider uses a self-signed certificate, put the
        path to its certificate here instead.
      type: string
    idp_ca_cert_path_upload:
      description: Idp ca cert path upload
      type: string
    idp_cert_path:
      description: Idp cert path
      type: string
    idp_cert_path_upload:
      description: Idp cert path upload
      type: string
    idp_entity_id:
      description: Idp entity id
      type: string
    idp_metadata_path:
      description: Idp metadata path
      type: string
    idp_metadata_path_upload:
      description: Idp metadata path upload
      type: string
    sp_cert_path:
      description: Sp cert path
      type: string
    sp_cert_path_upload:
      description: Sp cert path upload
      type: string
    sp_entity_id:
      description: Sp entity id
      type: string
    sp_key_path:
      description: Sp key path
      type: string
    sp_key_path_upload:
      description: Sp key path upload
      type: string
    type:
      default: SAML
      description: Discriminator `SAML`
      type: string
    username_attribute:
      description: Username attribute
      type: string
  required:
  - id
  - description
  - sp_entity_id
  - idp_entity_id
  - authorization_source_id
  type: object
