ConfigMaintenanceTaskSubTypePasswordOfTheDay:
  properties:
    id:
      description: Pfcron Name
      type: string
    schedule:
      description: The schedule for maintenance task (cron like spec).
      type: string
    status:
      description: Whether or not this task is enabled.<br>Requires a restart of pfcron
        to be effective.
      type: string
    type:
      default: password_of_the_day
      description: Discriminator `password_of_the_day`
      type: string
  required:
  - id
  - type
  type: object
