ConfigDomain:
  properties:
    ad_account_lockout_duration:
      description: How long will an account keep locked after hitting bad password
        threshold. In minutes
      type: integer
    ad_account_lockout_threshold:
      description: Max bad login attempts before an account is locked out automatically,
        default is 0, never locks.
      type: integer
    ad_fqdn:
      description: The FQDN of the Active Directory server
      type: string
    ad_old_password_allowed_period:
      description: Old Password Allowed Period in NTLM Authentication. In minutes
      type: integer
    ad_reset_account_lockout_counter_after:
      description: After how long will the lockout counter resets. In minutes.
      type: integer
    ad_server:
      description: The IPv4 of the Active Directory server
      type: string
    bind_dn:
      description: The username of a Domain Admin to use to join the server to the
        domain
      type: string
    bind_pass:
      description: The password of a Domain Admin to use to join the server to the
        domain. Will not be stored permanently and is only used while joining the
        domain.
      type: string
    dns_name:
      description: The DNS name (FQDN) of the domain.
      type: string
    dns_servers:
      description: The IP address(es) of the DNS server(s) for this domain. Comma
        delimited if multiple.
      type: string
    id:
      description: Specify a unique identifier for your configuration.<br/>This doesn't
        have to be related to your domain
      type: string
    machine_account_password:
      description: Password of the machine account to be added to Active Directory.
      type: string
    max_allowed_password_attempts_per_device:
      description: Maximum bad login attempt for a single device.
      type: integer
    nt_key_cache_enabled:
      description: Should the NT Key cache be enabled for this domain?
      type: string
    nt_key_cache_expire:
      description: The amount of seconds an entry should be cached.
      type: integer
    ntlm_auth_host:
      description: The IP address of NTLM auth API
      type: string
    ntlm_auth_port:
      description: The listening port of NTLM auth API.
      type: string
    ntlm_cache:
      description: Should the NTLM cache be enabled for this domain?
      type: string
    ntlm_cache_expiry:
      description: The amount of seconds an entry should be cached.
      type: integer
    ntlm_cache_source:
      description: The source to use to connect to your Active Directory server for
        NTLM caching.
      type: string
    ou:
      description: Use a specific OU for the PacketFence account. The OU string read
        from top to bottom without RDNs and delimited by a '/'. E.g. "Computers/Servers/Unix".
      type: string
    password_is_nt_hash:
      description: Password stored in the config file is NT hash.
      type: string
    registration:
      description: If this option is enabled, the device will be able to reach the
        Active Directory from the registration VLAN.
      type: string
    server_name:
      description: 'This server''s name (account name) in your Active Directory. ''%h''
        is a placeholder for this server hostname. In a cluster, you must use %h and
        ensure your hostnames are less than 14 characters. You can mix ''%h'' with
        a prefix or suffix (ex: ''pf-%h'') '
      type: string
    status:
      description: Enabled
      type: string
    sticky_dc:
      description: This is used to specify a sticky domain controller to connect to.
        If not specified, default '*' will be used to connect to any available domain
        controller
      type: string
    workgroup:
      description: Workgroup
      type: string
  required:
  - id
  - workgroup
  - ad_fqdn
  - ad_server
  - dns_servers
  - server_name
  - sticky_dc
  - dns_name
  - ou
  - machine_account_password
  type: object
