ConfigSyslogForwarderSubTypeFile:
  properties:
    all_logs:
      description: All logs
      type: string
    id:
      description: Syslog Name
      type: string
    logs:
      description: Logs
      items:
        description: Logs
        type: string
      type: array
    type:
      default: file
      description: Discriminator `file`
      type: string
  required:
  - id
  - type
  type: object
