ConfigFilterEnginesProvisioningFilter:
  description: 'Choose one of the request bodies by discriminator (`type`). '
  discriminator:
    mapping:
      google_workspace_chromebook: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeGoogleWorkspaceChromebook'
      intune: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeIntune'
      kandji: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeKandji'
    propertyName: type
  oneOf:
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeGoogleWorkspaceChromebook'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeIntune'
  - $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilterSubTypeKandji'
