ConfigProvisioningSubTypeIntune:
  properties:
    access_token:
      description: Access token
      type: string
    android_agent_download_uri:
      description: Android agent download uri
      type: string
    applicationID:
      description: ApplicationID
      type: string
    applicationSecret:
      description: Application Secret
      type: string
    apply_role:
      description: When enabled, this will apply the configured role to the endpoint
        if it is authorized in the provisioner.
      type: string
    autoregister:
      description: Whether or not devices should be automatically registered on the
        network if they are authorized in the provisioner.
      type: string
    category:
      description: Nodes with the selected roles will be affected
      items:
        description: Nodes with the selected roles will be affected
        type: string
      type: array
    description:
      description: Description
      type: string
    domains:
      description: Comma-separated list of domains that will be resolved with the
        correct IP addresses.
      type: string
    enforce:
      description: Whether or not the provisioner should be enforced. This will trigger
        checks to validate the device is compliant with the provisioner during RADIUS
        authentication and on the captive portal.
      type: string
    host:
      description: Host
      type: string
    id:
      description: Provisioning ID
      type: string
    ios_agent_download_uri:
      description: Ios agent download uri
      type: string
    loginUrl:
      description: LoginUrl
      type: string
    mac_osx_agent_download_uri:
      description: Mac osx agent download uri
      type: string
    non_compliance_security_event:
      description: Which security event should be raised when non compliance is detected
      type: string
    oses:
      description: Nodes with the selected OS will be affected
      items:
        description: Nodes with the selected OS will be affected
        type: string
      type: array
    pki_provider:
      description: PKI Provider
      type: string
    port:
      description: Port
      type: integer
    protocol:
      description: Protocol
      type: string
    role_to_apply:
      description: When "Apply role" is enabled, this defines the role to apply when
        the device is authorized with the provisioner.
      type: string
    rules:
      description: Rules to be applied
      items:
        description: Rules to be applied
        type: string
      type: array
    sync_pid:
      description: Whether or not the PID (username) should be synchronized from the
        provisioner to PacketFence.
      type: string
    tenantID:
      description: Tenant ID
      type: string
    type:
      default: intune
      description: Discriminator `intune`
      type: string
    windows_agent_download_uri:
      description: Windows agent download uri
      type: string
  required:
  - id
  - type
  - tenantID
  - applicationID
  - applicationSecret
  - port
  - windows_agent_download_uri
  - mac_osx_agent_download_uri
  - ios_agent_download_uri
  - android_agent_download_uri
  - domains
  type: object
