ConfigPkiProviderSubTypeScep:
  properties:
    ca_cert_path:
      description: Path of the CA that will generate your certificates
      type: string
    ca_cert_path_upload:
      description: Ca cert path upload
      type: string
    cn_attribute:
      description: Defines what attribute of the node to use as the common name during
        the certificate generation.
      type: string
    cn_format:
      description: Defines how the common name will be formated. %s will expand to
        the defined Common Name Attribute value
      type: string
    country:
      description: Country for the certificate
      type: string
    id:
      description: Id
      type: string
    locality:
      description: Locality for the certificate
      type: string
    organization:
      description: Organization for the certificate
      type: string
    organizational_unit:
      description: Organizational unit for the certificate
      type: string
    password:
      description: Password for the username filled in above
      type: string
    server_cert_path:
      description: Path of the RADIUS server authentication certificate
      type: string
    server_cert_path_upload:
      description: Server cert path upload
      type: string
    state:
      description: State for the certificate
      type: string
    type:
      default: scep
      description: Discriminator `scep`
      type: string
    url:
      description: The url used to connect to the SCEP PKI service
      type: string
    username:
      description: Username to connect to the SCEP PKI Service
      type: string
  required:
  - id
  - type
  type: object
