ConfigSourceSubTypePotd:
  properties:
    administration_rules:
      description: Administration rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    authentication_rules:
      description: Authentication rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    description:
      description: Description
      type: string
    id:
      description: Name
      type: string
    password_email_update:
      description: Email addresses to send the new generated password.
      type: string
    password_length:
      description: The length of the password to generate.
      type: integer
    password_rotation:
      description: Period of time after the password must be rotated.
      type: string
    realms:
      description: Realms that will be associated with this source (For the Portal/Admin
        GUI/RADIUS post-auth, not for FreeRADIUS proxy)
      items:
        description: Realms that will be associated with this source (For the Portal/Admin
          GUI/RADIUS post-auth, not for FreeRADIUS proxy)
        type: string
      type: array
    type:
      default: Potd
      description: Discriminator `Potd`
      type: string
  required:
  - id
  - description
  - password_length
  - password_email_update
  type: object
