ConfigPortalModuleSubTypeSurvey:
  properties:
    actions:
      description: Actions
      items:
        description: Action
        properties:
          type:
            description: Type
            type: string
          value:
            description: Value
            type: string
        type: object
      type: array
    description:
      description: The description that will be displayed to users
      type: string
    id:
      description: Identifier
      type: string
    survey_id:
      description: The survey to use in this portal module. Surveys are defined in
        survey.conf
      type: string
    template:
      description: The template to use to display the message
      type: string
    type:
      default: Survey
      description: Discriminator `Survey`
      type: string
  required:
  - id
  - description
  type: object
