ConfigSourceSubTypeKickbox:
  properties:
    administration_rules:
      description: Administration rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    api_key:
      description: Kickbox.io API key.
      type: string
    authentication_rules:
      description: Authentication rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    description:
      description: Description
      type: string
    email_required:
      description: Email required
      type: string
    id:
      description: Id
      type: string
    type:
      default: Kickbox
      description: Discriminator `Kickbox`
      type: string
  required:
  - id
  - description
  - api_key
  type: object
