ConfigMaintenanceTaskSubTypeNodeCleanup:
  properties:
    batch:
      default: '100'
      description: Amount of items that will be processed in each batch of this task.
        Batches are executed until there is no more items to process or until the
        timeout is reached.
      type: integer
    delete_window:
      default:
        interval: '0'
        unit: D
      description: How long can an unregistered node be inactive on the network before
        being deleted.<br>This shouldn't be used if you are using port-security
      properties:
        interval:
          default: '0'
          description: Interval
          type: integer
        unit:
          default: D
          description: Unit
          type: string
      type: object
    id:
      default: ~
      description: Pfcron Name
      type: string
    schedule:
      default: '@every 1m'
      description: The schedule for maintenance task (cron like spec).
      type: string
    status:
      default: disabled
      description: Whether or not this task is enabled.<br>Requires a restart of pfcron
        to be effective.
      type: string
    timeout:
      default:
        interval: '10'
        unit: s
      description: Maximum amount of time this task can run.
      properties:
        interval:
          default: '10'
          description: Interval
          type: integer
        unit:
          default: s
          description: Unit
          type: string
      type: object
    type:
      default: node_cleanup
      description: Discriminator `node_cleanup`
      type: string
      value: node_cleanup
    unreg_window:
      default:
        interval: '0'
        unit: D
      description: How long can a registered node be inactive on the network before
        it becomes unregistered
      properties:
        interval:
          default: '0'
          description: Interval
          type: integer
        unit:
          default: D
          description: Unit
          type: string
      type: object
    voip:
      default: enabled
      description: Enable voip device cleanup
      type: string
  required:
  - id
  - type
  type: object
