ConfigSourceSubTypeRadius:
  properties:
    administration_rules:
      description: Administration rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    authentication_rules:
      description: Authentication rules
      items:
        description: Rule - New (  )
        properties:
          actions:
            description: Actions
            items:
              description: Action
              properties:
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          conditions:
            description: Conditions
            items:
              description: Condition
              properties:
                attribute:
                  description: Attribute
                  type: string
                operator:
                  description: Operator
                  type: string
                type:
                  description: Type
                  type: string
                value:
                  description: Value
                  type: string
              type: object
            type: array
          description:
            description: Description
            type: string
          id:
            description: Name
            type: string
          match:
            description: Matches
            type: string
          status:
            description: Enable rule
            type: string
        type: object
      type: array
    description:
      description: Description
      type: string
    host:
      description: Host
      type: string
    id:
      description: Id
      type: string
    monitor:
      description: Do you want to monitor this source?
      type: string
    nas_ip_address:
      description: Nas ip address
      type: string
    options:
      description: Define options for FreeRADIUS home_server definition (if you use
        the source in the realm configuration). Need a radius restart.
      type: string
    port:
      description: If you use this source in the realm configuration the accounting
        port will be this port + 1
      type: integer
    realms:
      description: Realms that will be associated with this source (For the Portal/Admin
        GUI/RADIUS post-auth, not for FreeRADIUS proxy)
      items:
        description: Realms that will be associated with this source (For the Portal/Admin
          GUI/RADIUS post-auth, not for FreeRADIUS proxy)
        type: string
      type: array
    secret:
      description: Secret
      type: string
    timeout:
      description: Timeout
      type: integer
    type:
      default: RADIUS
      description: Discriminator `RADIUS`
      type: string
    use_connector:
      description: Use connector
      type: string
  required:
  - id
  - description
  - host
  - port
  - secret
  - timeout
  type: object
