ConfigMaintenanceTaskSubTypeIp6logCleanup:
  properties:
    batch:
      description: Amount of items that will be processed in each batch of this task.
        Batches are executed until there is no more items to process or until the
        timeout is reached.
      type: integer
    id:
      description: Pfcron Name
      type: string
    rotate:
      description: Enable or disable ip6log rotation (moving ip6log_history records
        to ip6log_archive)<br>If disabled, this task will delete from the ip6log_history
        table rather than the ip6log_archive.
      type: string
    rotate_batch:
      description: Amount of items that will be processed in each batch of this task.
        Batches are executed until there is no more items to process or until the
        timeout is reached.
      type: integer
    rotate_timeout:
      description: Maximum amount of time this task can run.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    rotate_window:
      description: How long to keep ip6log history entry before rotating it to ip6log
        archive.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    schedule:
      description: The schedule for maintenance task (cron like spec).
      type: string
    status:
      description: Whether or not this task is enabled.<br>Requires a restart of pfcron
        to be effective.
      type: string
    timeout:
      description: Maximum amount of time this task can run.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    type:
      default: ip6log_cleanup
      description: Discriminator `ip6log_cleanup`
      type: string
    window:
      description: How long to keep a ip6log archive entry before deleting it (or
        ip6log history if rotation is disabled)
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
  required:
  - id
  - type
  type: object
