ConfigSourceSubTypeStripe:
  properties:
    create_local_account:
      description: Create a local account on the PacketFence system based on the username
        provided.
      type: string
    currency:
      description: Currency
      type: string
    customer_portal:
      description: Customer portal
      type: string
    description:
      description: Description
      type: string
    domains:
      description: Comma separated list of domains that will be resolve with the correct
        IP addresses.
      type: string
    hash_passwords:
      description: The algorithm used to hash the passwords in the database.This will
        only affect newly created or reset passwords.
      type: string
    id:
      description: Id
      type: string
    local_account_expiration:
      description: Local account expiration
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    local_account_logins:
      description: The amount of times, the local account can be used after its created.
        0 means infinite.
      type: integer
    password_length:
      description: The length of the password to generate.
      type: integer
    publishable_key:
      description: Publishable key
      type: string
    secret_key:
      description: Secret key
      type: string
    send_email_confirmation:
      description: Send billing confirmation
      type: string
    style:
      description: The type of payment the user will make. Charge is a one time fee,
        subscription will be a recurring fee.
      type: string
    test_mode:
      description: Test mode
      type: string
    type:
      default: Stripe
      description: Discriminator `Stripe`
      type: string
  required:
  - id
  - description
  - hash_passwords
  - password_length
  - secret_key
  - publishable_key
  - domains
  type: object
