- hosts: service_samba
  name: Manage Samba service
  become: True

  collections:
    - debops.debops
    - debops.roles01
    - debops.roles02
    - debops.roles03

  #roles:
  #  - role: samba

  tasks:
  - name: Disable IPV6
    ansible.posix.sysctl:
      name: "{{ item }}"
      value: '1'
      sysctl_set: true
    loop:
    - "net.ipv6.conf.all.disable_ipv6"
    - "net.ipv6.conf.default.disable_ipv6"
    - "net.ipv6.conf.lo.disable_ipv6"

  - name: Install Samba packages
    ansible.builtin.package:
      name: '{{ item }}'
      state: 'present'
    loop:
    - gnupg
    - lsb-release
    - python3-pexpect

  - name: Reboot
    ansible.builtin.reboot:

  - name: Wait for the reboot and reconnect 
    wait_for_connection:

  - name: Pause for 10 seconds after reboot
    ansible.builtin.pause:
      seconds: 10

  - name: Download file with check (sha256)
    ansible.builtin.get_url:
      url: http://samba.tranquil.it/tissamba-pubkey.gpg
      dest: /root/tissamba-pubkey.gpg
      checksum: sha256:bd0f7140edd098031fcb36106b24a6837b067f1c847f72cf262fa012f14ce2dd

  - name: Add samba gpg
    ansible.builtin.apt_key:
      file: /root/tissamba-pubkey.gpg
      state: present
    
  - name: add apt source
    ansible.builtin.apt_repository:
      repo: "deb https://samba.tranquil.it/debian/samba-4.16/ bullseye main"
      state: present

  - name: update and upgrade
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes

  - name: Install Samba packages
    ansible.builtin.package:
      name: '{{ item }}'
      state: 'present'
    loop: '{{ samba__base_packages }}'

  - name: Stop and Mask Services
    ansible.builtin.systemd:
      enabled: no
      state: stopped
      masked:  yes
      name: "{{ item }}"
    loop: "{{ samba__services_to_stop }}"

  - name: Remove config files
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - "/etc/samba/smb.conf"
      - "/etc/krb5.conf"

  - name: change krb5.conf
    ansible.builtin.blockinfile:
      create: true
      dest: /etc/krb5.conf
      content: |
         [libdefaults]
            default_realm = "{{ dns_domain_upper }}"
            dns_lookup_kdc = "{{ domain_setup__kdc }}"
            dns_lookup_realm = "{{ domain_setup__realm }}"
         
         [realms]
            "{{ dns_domain_upper }}" = {
              "admin_server = LINUX03.{{ dns_domain_upper }}"
              "kdc = LINUX03.{{ dns_domain_upper }}"
         }
         
         [domain_realm]
           "{{ dns_domain }} = {{ dns_domain_upper }}"
           ".{{ dns_domain }} = {{ dns_domain_upper }}"

  - name: Adding localhost in resolv.conf
    ansible.builtin.lineinfile:
      path: /etc/dhcp/dhclient.conf
      line: prepend domain-name-servers 127.0.0.1;
      state: present
      create: true

  - name: Configure Samba
    ansible.builtin.shell:
      cmd: "{{ item }}"
    loop:
    - "samba-tool domain provision --realm={{ dns_domain_upper }} --domain {{ samba__global_custom.workgroup }} --server-role=dc"

  - name: Configure Samba admin password
    ansible.builtin.expect:
      command: "{{ item }}"
      responses:
        (?i)new\s(?i)password: "{{ domain_setup__password }}"
        (?i)retype\s(?i)password: "{{ domain_setup__password }}"
    loop:
    - "samba-tool user setpassword {{ domain_setup__username }}"

  - name: Remove config files
    file:
      path: "{{ item }}"
      state: absent
    loop:
    - "/var/lib/samba/private/krb5.conf"

  - name: Creating a symlink
    ansible.builtin.file:
      src: "/etc/krb5.conf"
      dest: "/var/lib/samba/private/krb5.conf"
      state: link

  - name: Unmask and start Services
    ansible.builtin.systemd:
      enabled: yes
      state: restarted
      masked: no
      name: "{{ item }}"
    loop:
    - "samba-ad-dc" 

  - name: Reboot
    ansible.builtin.reboot:

  - name: Wait for the reboot and reconnect
    wait_for_connection:

  - name: Pause for 10 seconds after reboot
    ansible.builtin.pause:
      seconds: 10

  - name: Load kinit with admin password
    ansible.builtin.expect:
      command: "{{ item }}"
      responses:
        (?i)password.*: "{{ domain_setup__password }}"
    loop:
    - "kinit administrator"

  - name: Klist Samba
    ansible.builtin.shell:
      cmd: "{{ item }}"
    loop:
    - "klist"

  - name: Configure Samba admin password
    ansible.builtin.expect:
      command: "{{ item }}"
      responses:
        (?i)new\s(?i)password: "P@ck3tF3nc3pass"
        (?i)retype\s(?i)password: "P@ck3tF3nc3pass"
    loop:
    - "samba-tool user add --username=packetfence --mail-address=packetfence@{{ dns_domain }} --workgroup={{ dns_domain_upper }}"

  - name: Configure Samba AD Stuff
    ansible.builtin.shell:
      cmd: "{{ item }}"
    loop:
    - "samba-tool user setexpiry packetfence --noexpiry"
    - "samba-tool group add sponsor"
    - "samba-tool group add IT"
    - "samba-tool group add sponsor IT"
    - "samba-tool group addmembers sponsor packetfence"
    - "samba-tool group addmembers IT packetfence"
    #- "samba-tool group addmembers Domain Users packetfence"

