/api/v1/config/filter_engines/provisioning_filters:
  description: Configure vlan filters
  get:
    description: List all items.
    operationId: api.v1.Config.FilterEngines.Provisioning.list
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFiltersList'
        description: Request successful. Response contains a list of resources.
      '401':
        $ref: '#/components/responses/Forbidden'
    tags:
    - Config/FilterEngines/ProvisioningFilters
  options:
    description: Get meta for a new item.
    operationId: api.v1.Config.FilterEngines.Provisioning.options
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFiltersMeta'
        description: Request successful. Response contains meta for a resource.
      '401':
        $ref: '#/components/responses/Forbidden'
      '404':
        $ref: '#/components/responses/NotFound'
    tags:
    - Config/FilterEngines/ProvisioningFilters
  post:
    description: Create a new item.
    operationId: api.v1.Config.FilterEngines.Provisioning.create
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigFilterEnginesProvisioningFilter'
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '401':
        $ref: '#/components/responses/Forbidden'
      '409':
        $ref: '#/components/responses/Duplicate'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
    tags:
    - Config/FilterEngines/ProvisioningFilters
